# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
  
  
#install: travis_retry composer install --no-interaction --ignore-platform-reqs --no-scripts --prefer-source
install:
#  - if [ "$TRAVIS_PHP_VERSION" != "5.2" ]; then travis_retry composer install --no-interaction --prefer-source

# Commands to be run before your environment runs.
before_script:
#  - composer install --dev

#  - for travis integration to code climate
after_script:
  - vendor/bin/test-reporter

# Commands you want to run that will verify your build.
script: phpunit --coverage-text

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: never